### ISSUE TITLE
0.4-dev LoadError: syntax: "ID::Int=0" inside type definition is reserved

### ISSUE THREAD

**Issue by paulmthompson** [JuliaLang/Tk.jl#105]
Version 0.4.0-dev+5765 (2015-07-02 21:46 UTC)
Commit 8ad0c1c (0 days old master)
x86_64-linux-gnu

julia> Pkg.test("Tk")
INFO: Computing test dependencies for Tk...
INFO: No packages to install, update or remove
INFO: Testing Tk

WARNING: deprecated syntax "< {" at /home/nicolelislab/.julia/v0.4/FixedPointNumbers/src/fixed32.jl:20.
Use "<{" instead.

WARNING: deprecated syntax "< {" at /home/nicolelislab/.julia/v0.4/FixedPointNumbers/src/ufixed.jl:91.
Use "<{" instead.
ERROR: LoadError: LoadError: LoadError: syntax: "ID::Int=0" inside type definition is reserved
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
 in include at ./boot.jl:254
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:306
 in _start at ./client.jl:406
while loading /home/nicolelislab/.julia/v0.4/Tk/src/tkwidget.jl, in expression starting on line 125
while loading /home/nicolelislab/.julia/v0.4/Tk/src/Tk.jl, in expression starting on line 35
while loading /home/nicolelislab/.julia/v0.4/Tk/test/runtests.jl, in expression starting on line 2
=================================[ ERROR: Tk ]==================================

failed process: Process(`/home/nicolelislab/julia/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/nicolelislab/.julia/v0.4/Tk/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: Tk had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:746
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71

**Comment by timholy** [comment]
Fixed by #106.
