### ISSUE TITLE
"Can't find init.tcl" on Windows

### ISSUE THREAD

**Issue by MikeInnes** [JuliaLang/Tk.jl#67]
When I run `using Tk` I get the error
```
ERROR: TclError(
"error initializing Tcl: Can't find a usable init.tcl in the following directories: 
    {C:\\Ruby200-x64\\share\\tcl} C:/Ruby200-x64/share/tcl8.5 C:/Ruby200-x64/lib/tcl8.5 C:/Users/Mike/Desktop/julia-05c6461b55/lib/tcl8.5 C:/Users/Mike/Desktop/lib/tcl8.5 C:/Users/Mike/Desktop/julia-05c6461b55/library C:/Users/Mike/Desktop/library C:/Users/Mike/Desktop/tcl8.5.12/library C:/Users/Mike/tcl8.5.12/library

    This probably means that Tcl wasn't installed properly.
")
 in init at C:\Users\Mike\.julia\Tk\src\tkwidget.jl:58
WARNING: backtraces on your platform are often misleading or partially incorrect

at C:\Users\Mike\.julia\Tk\src\tkwidget.jl:452
at C:\Users\Mike\.julia\Tk\src\Tk.jl:25
```
Installing ActiveTCL didn't help, and copying its `init.tcl` file to one of these locations caused `using Tk` to hang until I reinstalled Julia. For what it's worth, git gui (using Tk) runs fine on my system.

**Comment by joa-quim** [comment]
I'm still getting this error even after starting with a new .julia/v0.4 (didn't want to try the same with v0.3).
I also noticed one thing. I copied one init.tcl that I found in WinRPM into `julia-0.3.4\lib\tcl8.5` and now it also complains that
`version conflict for package \"Tcl\": have 8.5.2, need exactly 8.5.15\nversion conflict for package \"Tcl\": have 8.5.2, need exactly 8.5.15\`
So the `init.tcl` in `C:\j\.julia\v0.3\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\share\tcl8.5` does not go along with the dll in `C:\j\.julia\v0.3\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\tcl85.dll` which claims to be version 8.5.2.15

**Comment by dchansen** [comment]
The issues seems to be that Julia finds a Tcl installation from another programming language (Python or Ruby for instance), which does not match the version needed for Tk.jl.
