### ISSUE TITLE
Warning in Julia 0.4

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/Tk.jl#86]
After the latest pull of the interpreter and Tk:

>WARNING: deprecated syntax "{a for a in b}" at /home/julio/.julia/v0.4/Tk/src/tkwidget.jl:142.
Use "Any[a for a in b]" instead.

>WARNING: deprecated syntax "{a=>b, ...}" at /home/julio/.julia/v0.4/Tk/src/core.jl:83.
Use "Dict{Any,Any}(a=>b, ...)" instead.

>WARNING: deprecated syntax "{a=>b, ...}" at /home/julio/.julia/v0.4/Tk/src/core.jl:204.
Use "Dict{Any,Any}(a=>b, ...)" instead.

>WARNING: deprecated syntax "{a=>b, ...}" at /home/julio/.julia/v0.4/Tk/src/containers.jl:70.
Use "Dict{Any,Any}(a=>b, ...)" instead.

**Comment by juliohm** [comment]
The warning above were fixed, now I get new warnings:

>Warning: using Tk.parent in module Main conflicts with an existing identifier.
Warning: using Tk.Text in module Main conflicts with an existing identifier.
Warning: using Tk.bind in module Main conflicts with an existing identifier.

**Comment by jiahao** [comment]
I could not reproduce the conflicts. Did you by any chance try to load the package twice?

I'm tagging a new version. Please reopen if there is still an issue.

**Comment by juliohm** [comment]
I still get the warnings. I start Julia and type:

```julia
using Tk
```

**Comment by jiahao** [comment]
I don't get these warnings anymore. Can you try `Pkg.update()`?

My version info:

```jl
julia> Pkg.installed("Tk")
v"0.3.1"

julia> versioninfo()
Julia Version 0.4.0-dev+4258
Commit c722b5d (2015-04-14 23:02 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by juliohm** [comment]
Same package version, my Julia is older: `Julia Version 0.4.0-dev+4059`.

**Comment by jiahao** [comment]
What is the output of `Pkg.status("Tk")`?

```jl
julia> Pkg.status("Tk")
 - Tk                            0.3.1
```

**Comment by juliohm** [comment]
The same as yours.

**Comment by jiahao** [comment]
Did you by any chance precompile Tk in base/userimg.jl?

**Comment by juliohm** [comment]
Not that I know. I installed the package as usual with the manager.
