### ISSUE TITLE
TclError 

### ISSUE THREAD

**Issue by dolejm1** [JuliaLang/Tk.jl#87]
I've updated all the packages on my w7 machine and got:

  | | |_| | | | (_| |  |  Version 0.3.2+2 (2014-10-22 01:21 UTC)
 _/ |\__'_|_|_|\__'_|  |  release-0.3/6babc84* (fork: 180 commits, 134 days)
|__/                   |  x86_64-w64-mingw32

julia> Pkg.installed("Tk")
v"0.2.16"

julia> using Tk
ERROR: TclError("error initializing Tcl: Can't find a usable init.tcl in the following directories: \n    {C:\\Python34\\share\\
tcl} C:/Python34/share/tcl8.6 C:/Python34/lib/tcl8.6 {C:/Program Files/Julia-0.3.2/lib/tcl8.6} {C:/Program Files/lib/tcl8.6} {C:
/Program Files/Julia-0.3.2/library} {C:/Program Files/library} {C:/Program Files/tcl8.6.1/library} C:/tcl8.6.1/library\n\n\n\nTh
is probably means that Tcl wasn't installed properly.\n")
 in init at C:\Users\dolejm1\.julia\v0.3\Tk\src\tkwidget.jl:58
while loading C:\Users\dolejm1\.julia\v0.3\Tk\src\tkwidget.jl, in expression starting on line 453
while loading C:\Users\dolejm1\.julia\v0.3\Tk\src\Tk.jl, in expression starting on line 25

**Comment by tkelman** [comment]
Is your Python installation at `C:\Python32` 32 or 64 bit?

**Comment by dolejm1** [comment]
64 bit.

**Comment by tkelman** [comment]
Did it look like `Pkg.build("Tk")` successfully installed a Tk library? It should be downloading one.

**Comment by dolejm1** [comment]
It works OK after building Tk

**Comment by tkelman** [comment]
Great, should we close this issue then?

**Comment by dolejm1** [comment]
Yes
